---
env:
  PACKAGE_NAME: atuin
  PACKAGE_VERSION: v18.3.0
  PACKAGE_DESCRIPTION: Magical shell History
  BINARY_NAME: atuin

name: Build, package and upload
"on":
  push:
    paths-ignore:
      - "*.md"
      - LICENSE
      - .github/renovate.json
      - .gitignore
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target:
#          - x86_64-unknown-linux-gnu
#          - arm-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
      fail-fast: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: atuinsh/atuin.git
          ref: ${{ env.PACKAGE_VERSION }}
      - run: sudo apt-get update &&  sudo apt-get install -y protobuf-compiler
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true
      - name: Upload build artifact
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: binary-${{ matrix.target }}
          path: target/**/release/${{ env.BINARY_NAME }}
  build-package:
    name: Build Deb Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_arch:
          - x86_64-unknown-linux-gnu
          - arm-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
      fail-fast: true
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Download build artifact
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4
        with:
          name: binary-${{ matrix.rust_arch }}
      - name: Package
        run: ./package.sh
        env:
          DEB_NAME: ${{ env.PACKAGE_NAME }}
          APP_DESCRIPTION: ${{ env.PACKAGE_DESCRIPTION }}
          APP_URL: https://atuin.sh/
          ARCH: ${{ matrix.rust_arch }}
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
      - name: Upload build artifact
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: deb-package-${{ matrix.rust_arch }}
          path: "*.deb"
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: build-package
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4
        with:
          pattern: deb-package-*
      - name: Upload to Apt repo
        env:
          APT_CREDENTIALS: ${{ secrets.APT_CREDENTIALS }}
          APT_KEY_PASSPHRASE: ${{ secrets.APT_KEY_PASSPHRASE }}
        run: ./publish.sh
